# Generated by Django 5.0.2 on 2024-02-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='имя')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='тема вашего текста', max_length=200, verbose_name='тема')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='имя')),
                ('summary', models.TextField(verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, help_text='вдохновляющие картины', null=True, upload_to='media/images/posts', verbose_name='картинки')),
                ('song', models.FileField(blank=True, help_text='музыка', null=True, upload_to='media/song/posts', verbose_name='Звук')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/posts', verbose_name='Видео')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.author', verbose_name='автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='тема')),
            ],
        ),
    ]
